name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-varsion }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{  matrix.node-varsion }}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build
